[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
VerbosePkgLists
ParallelDownloads = 10
ILoveCandy

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[archlinuxcn]
SigLevel = Optional TrustAll
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
Server = https://mirrors.aliyun.com/archlinuxcn/$arch
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
Server = https://mirror.sjtu.edu.cn/archlinuxcn/$arch
Server = https://mirrors.huaweicloud.com/archlinuxcn/$arch

## ===== 中国香港 =====
Server = https://mirror-hk.koddos.net/archlinuxcn/$arch

## ===== 新加坡 =====
Server = https://sg.mirror.rackspace.com/archlinuxcn/$arch

## ===== 日本 =====
Server = https://jp.mirror.rackspace.com/archlinuxcn/$arch

## ===== 韩国 =====
Server = https://ftp.harukasan.org/archlinuxcn/$arch

Include = /etc/pacman.d/mirrorlist-archlinuxcn

